### ISSUE TITLE
Doubt on how it's deployed

### ISSUE THREAD

**Issue by mehul1011** [bryanhannes/ameliorated-chat#10]
Sorry for opening a doubt as an issue,
Just wanted to know your full-stack deployment strategies WRT Angular, Nest, and putting it on Vercel altogether.

Maybe more clarification of this on readme might help.

Thanks

**Comment by bryanhannes** [comment]
Hi @mehul1011 
This repo does not contain a Nest project (anymore), the Angular code calls the OpenAI API directly.

The last time I looked into deploying a Nest project to Nest, it was not possible.

Hope this clarifies your doubt :)

**Comment by mehul1011** [comment]
> Hi @mehul1011 
> This repo does not contain a Nest project (anymore), the Angular code calls the OpenAI API directly.
> 
> The last time I looked into deploying a Nest project to Nest, it was not possible.
> 
> Hope this clarifies your doubt :)
> 

Thanks for the clarification.

One more thing I wanted to ask, i assume you would be using openai API key, how you fetching/feeding openai API key stored in vercel to angular, since there is not concept of .env file, but there is environment.ts and through this the application uses it throughout.

How you get my point, let me know for any clarification needed.

Thanks

**Comment by bryanhannes** [comment]
> > Hi @mehul1011
> > This repo does not contain a Nest project (anymore), the Angular code calls the OpenAI API directly.
> > The last time I looked into deploying a Nest project to Nest, it was not possible.
> > Hope this clarifies your doubt :)
> 
> Thanks for the clarification.
> 
> One more thing I wanted to ask, i assume you would be using openai API key, how you fetching/feeding openai API key stored in vercel to angular, since there is not concept of .env file, but there is environment.ts and through this the application uses it throughout.
> 
> How you get my point, let me know for any clarification needed.
> 
> Thanks

In the case of AmelioratedChat, you have to provide the API key yourself via a popup, so not related to an .env file.

How I normally do configuration in my Angular applications is by loading the config in via an external JSON file, which I include via a Docker volume. See this video and check out the linked repo as well for a full example: https://blog.bryanhannes.com/why-you-should-externalize-angular-configuration/

**Comment by mehul1011** [comment]
> > > Hi @mehul1011
> > > This repo does not contain a Nest project (anymore), the Angular code calls the OpenAI API directly.
> > > The last time I looked into deploying a Nest project to Nest, it was not possible.
> > > Hope this clarifies your doubt :)
> > 
> > Thanks for the clarification.
> > 
> > One more thing I wanted to ask, i assume you would be using openai API key, how you fetching/feeding openai API key stored in vercel to angular, since there is not concept of .env file, but there is environment.ts and through this the application uses it throughout.
> > 
> > How you get my point, let me know for any clarification needed.
> > 
> > Thanks
> 
> In the case of AmelioratedChat, you have to provide the API key yourself via a popup, so not related to an .env file.
> 
> How I normally do configuration in my Angular applications is by loading the config in via an external JSON file, which I include via a Docker volume. See this video and check out the linked repo as well for a full example: https://blog.bryanhannes.com/why-you-should-externalize-angular-configuration/

Excellent this is what I wanted to explore, thanks a lot.
